### ISSUE TITLE
Requesting to create PR code supporting WordBase-2048 or get feedback on the idea

### ISSUE THREAD

**Issue by will-richards-ii** [yocto/yoclib-multibase-php#1]
I would like to discuss and solicit me working on a PR to add another base see: https://github.com/multiformats/multibase/issues/89

**Comment by ben221199** [comment]
As soon as you have worked out your idea and have your base merged into https://github.com/multiformats/multibase, I will update this library to support that base too. For now, just take the advise in https://github.com/multiformats/multibase/issues/89#issuecomment-987547870. And please, don't spam next time. 😛
